language: php

env:
  - OPCODE_CACHE=apc

php:
  - 5.3

before_script:
  - composer self-update
  - composer install --dev
  - phpunit -c travis.phpunit.xml

after_script:
  - php vendor/bin/coveralls -vvv --exclude-no-stmt
