<?php

namespace Liip\Drupal\Modules\Registry;

use Assert\Assertion;
use Assert\InvalidArgumentException;
use Psr\Log\LoggerAwareInterface;
use Psr\Log\LoggerInterface;
use Psr\Log\NullLogger;

class Multiply extends Registry implements LoggerAwareInterface
{
    /**
     * @var Registry[]
     */
    protected $registries = array();
    /**
     * @var LoggerInterface
     */
    protected $logger;
    /**
     * @var FactoryInterface
     */
    protected $factory;


    /**
     * @param string $section
     * @param Assertion $assertion
     * @param array $registries
     */
    public function __construct($section, Assertion $assertion, array $registries)
    {
        parent::__construct($section, $assertion);

        $this->registries = $registries;
    }

    /**
     * Shall delete the current registry from the database.
     */
    public function destroy()
    {
        // TODO: Implement destroy() method.
    }

    /**
     * Shall register a new section in the registry
     */
    public function init()
    {
        // TODO: Implement init() method.
    }

    /**
     * Provides the current set of registered items.
     * @return array
     */
    public function getContent()
    {
        $content = parent::getContent();

        if (empty($content)) {

            $iteration = 0;
            $content = $this->readUntilNotEmpty($iteration);
            $this->registry[$this->section] = $content;
        }

        return $content;
    }

    /**
     * Iterates over every registered registry and trys to find some content.
     *
     * @param integer $it
     *
     * @return array
     */
    protected function readUntilNotEmpty($it)
    {
        try {

            /** @var Registry $registry */
            $registry = $this->getFactory()->getRegistry($it, $this->section, $this->assertion);

        } catch (InvalidArgumentException $e) {

            $this->getLogger()->warning($e->getMessage());
            return array();
        }

        $content = $registry->getContent();

        if (empty($content)) {

            $this->getLogger()->warning('The registry ("' . get_class($registry) . '") did not provide any content.');
            $content = $this->readUntilNotEmpty(++$it);
        }

        return $content;
    }

    /**
     * Finds the item corresponding to the provided identifier in the registry.
     *
     * @param string $identifier
     * @param null $default
     *
     * @return mixed
     */
    public function getContentById($identifier, $default = null)
    {
        try {
            $content = parent::getContentById($identifier, $default);

        } catch (InvalidArgumentException $e) {

            $this->getLogger()->notice($e->getMessage());
            $content = array();
        }

        if (empty($content)) {

            $contents = $this->getContent();

            if (!empty($contents[$identifier])) {

                $content = $contents[$identifier];
            } else {

                return $default;
            }
        }

        return $content;
    }

    /**
     * Adds an item to the register.
     *
     * @param string $identifier
     * @param mixed $value
     *
     * @throws RegistryException
     * @return void
     */
    public function register($identifier, $value)
    {
        parent::register($identifier, $value); // TODO: Change the autogenerated stub
    }

    /**
     * Determines if the given identifier refers to a registry item.
     *
     * @param string $identifier
     *
     * @return bool
     * @throws \Assert\InvalidArgumentException in case the $identifier is not a string.
     */
    public function isRegistered($identifier)
    {
        return parent::isRegistered($identifier); // TODO: Change the autogenerated stub
    }

    /**
     * Replaces the content of the item identified by it's registration key by the new value.
     *
     * @param string $identifier
     * @param mixed $value
     *
     * @throws RegistryException
     */
    public function replace($identifier, $value)
    {
        parent::replace($identifier, $value); // TODO: Change the autogenerated stub
    }

    /**
     * Removes an item off the register.
     *
     * @param string $identifier
     *
     * @throws RegistryException
     */
    public function unregister($identifier)
    {
        parent::unregister($identifier); // TODO: Change the autogenerated stub
    }

    /**
     * Sets a logger instance on the object
     *
     * @param \Psr\Log\LoggerInterface $logger
     *
     * @return null
     */
    public function setLogger(LoggerInterface $logger)
    {
        $this->logger = $logger;
    }

    /**
     * Provides an instance of an implementation to the Psr\Log\LoggerInterface;
     * @return \Psr\Log\LoggerInterface
     */
    public function getLogger()
    {
        if (empty($this->logger)) {
            $this->logger = new NullLogger();
        }

        return $this->logger;
    }

    /**
     * Sets a factory instance on the object
     *
     * @param FactoryInterface $factory
     *
     * @return null
     */
    public function setFactory(FactoryInterface $factory)
    {
        $this->factory = $factory;
    }

    /**
     * Provides an instance of an implementation to the FactoryInterface;
     * @return FactoryInterface
     */
    public function getFactory()
    {
        if (empty($this->factory)) {
            $this->factory = new Factory($this->registries);
        }

        return $this->factory;
    }
}
